-- Find total customers by state
SELECT
    state,
    COUNT(customer_id) AS total_customers
FROM customers
GROUP BY state
ORDER BY total_customers DESC;

-- Find total customers by city
SELECT
    city,
    COUNT(customer_id) AS total_customers
FROM customers
GROUP BY city
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
    c.category_name,
    COUNT(p.product_id) AS total_products
FROM categories AS c
LEFT JOIN products AS p
    ON
        c.category_id = p.category_id
GROUP BY c.category_name
ORDER BY total_products DESC;

-- What is the average price in each category?
SELECT
    c.category_name,
    ROUND(AVG(p.list_price), 2) AS avg_price
FROM categories AS c
LEFT JOIN products AS p
    ON
        c.category_id = p.category_id
GROUP BY c.category_name
ORDER BY avg_price DESC;

-- What is the total revenue generated for each category?
SELECT
    c.category_name,
    SUM(oi.total_value) AS total_revenue
FROM categories AS c
LEFT JOIN products AS p
    ON
        c.category_id = p.category_id
LEFT JOIN order_items AS oi
    ON
        p.product_id = oi.product_id
GROUP BY c.category_name
ORDER BY total_revenue DESC;

-- What is the total revenue generated by each customer?
SELECT
    c.customer_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    SUM(oi.total_value) AS total_revenue
FROM customers AS c
LEFT JOIN orders AS o
    ON
        c.customer_id = o.customer_id
LEFT JOIN order_items AS oi
    ON
        o.order_id = oi.order_id
GROUP BY c.customer_id, customer_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across state?
SELECT
    c.state,
    SUM(oi.quantity) AS total_quanity
FROM customers AS c
LEFT JOIN orders AS o
    ON
        c.customer_id = o.customer_id
LEFT JOIN order_items AS oi
    ON
        o.order_id = oi.order_id
GROUP BY c.state
ORDER BY total_quanity DESC;

-- What is the total revenue generated for each stores?
SELECT
    s.store_id,
    s.store_name,
    SUM(oi.total_value) AS total_revenue
FROM stores AS s
LEFT JOIN orders AS o
    ON
        s.store_id = o.store_id
LEFT JOIN order_items AS oi
    ON
        o.order_id = oi.order_id
GROUP BY s.store_id, s.store_name
ORDER BY total_revenue DESC;


-- What is the total revenue generated for each brands?
SELECT
    b.brand_name,
    COALESCE(SUM(oi.total_value), 0) AS total_revenue
FROM brands AS b
LEFT JOIN products AS p
    ON
        b.brand_id = p.brand_id
LEFT JOIN order_items AS oi
    ON
        p.product_id = oi.product_id
GROUP BY b.brand_name
ORDER BY total_revenue DESC;
