-- Find total customers by state
SELECT
    state,
    COUNT(customer_id) AS total_customers
FROM customers
GROUP BY state
ORDER BY total_customers DESC;

-- Find total customers by city
SELECT
    city,
    COUNT(customer_id) AS total_customers
FROM customers
GROUP BY city
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
    C.category_name,
    COUNT(P.product_id) AS total_products
FROM categories AS C
LEFT JOIN products AS P ON
P.category_id = C.category_id
GROUP BY C.category_name
ORDER BY total_products DESC;

-- What is the average price in each category?
SELECT
    C.category_name,
    ROUND(AVG(P.list_price),2) AS avg_price
FROM categories AS C
LEFT JOIN products AS P ON
P.category_id = C.category_id
GROUP BY C.category_name
ORDER BY avg_price DESC;

-- What is the total revenue generated for each category?
SELECT
    C.category_name,
    SUM(OI.total_value) AS total_revenue
FROM categories AS C
LEFT JOIN products AS P ON
P.category_id = C.category_id
LEFT JOIN order_items AS OI ON
OI.product_id = P.product_id
GROUP BY C.category_name
ORDER BY total_revenue DESC;

-- What is the total revenue generated by each customer?
SELECT
    C.customer_id,
    CONCAT(C.first_name,' ',C.last_name) AS customer_name,
    SUM(OI.total_value) AS total_revenue
FROM customers AS C
LEFT JOIN orders AS O ON
C.customer_id = O.customer_id
LEFT JOIN order_items AS OI ON
OI.order_id = O.order_id
GROUP BY C.customer_id, customer_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across state?
SELECT
    C.state,
    SUM(OI.quantity) AS total_quanity
FROM customers AS C
LEFT JOIN orders AS O ON
C.customer_id = O.customer_id
LEFT JOIN order_items AS OI ON
OI.order_id = O.order_id
GROUP BY C.state
ORDER BY total_quanity DESC;

-- What is the total revenue generated for each stores?
SELECT
    S.store_id,
    S.store_name,
    SUM(OI.total_value) AS total_revenue
FROM stores AS S
LEFT JOIN orders AS O ON
S.store_id = O.store_id
LEFT JOIN order_items AS OI ON
OI.order_id = O.order_id
GROUP BY S.store_id, S.store_name
ORDER BY total_revenue DESC;


-- What is the total revenue generated for each brands?
SELECT
    B.brand_name,
    COALESCE(SUM(OI.total_value),0) AS total_revenue
FROM brands AS B
LEFT JOIN products AS P ON
P.brand_id = B.brand_id
LEFT JOIN order_items AS OI ON
OI.product_id = p.product_id
GROUP BY B.brand_name
ORDER BY total_revenue DESC;