-- Which 5 products Generating the Highest Revenue?
-- Simple Ranking
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    COALESCE(SUM(OI.TOTAL_VALUE), 0) AS TOTAL_REVENUE
FROM PRODUCTS AS P
LEFT JOIN ORDER_ITEMS AS OI
    ON
        P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;

-- Complex but Flexibly Ranking Using Window Functions
SELECT
    X.PRODUCT_ID,
    X.PRODUCT_NAME,
    X.TOTAL_REVENUE
FROM (
    SELECT
        P.PRODUCT_ID,
        P.PRODUCT_NAME,
        COALESCE(SUM(OI.TOTAL_VALUE), 0) AS TOTAL_REVENUE,
        DENSE_RANK()
            OVER (ORDER BY COALESCE(SUM(OI.TOTAL_VALUE), 0) DESC) AS RNK
    FROM PRODUCTS AS P
    LEFT JOIN ORDER_ITEMS AS OI
        ON
            P.PRODUCT_ID = OI.PRODUCT_ID
    GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
    ORDER BY TOTAL_REVENUE DESC
) AS X
WHERE X.RNK <= 5;

-- What are the 5 worst-performing products in terms of sales?
SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    COALESCE(SUM(OI.TOTAL_VALUE), 0) AS TOTAL_REVENUE
FROM PRODUCTS AS P
LEFT JOIN ORDER_ITEMS AS OI
    ON
        P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE ASC
LIMIT 5;

-- Find the top 10 customers who have generated the highest revenue
SELECT
    X.CUSTOMER_ID,
    X.CUSTOMER_NAME,
    X.TOTAL_REVENUE
FROM (
    SELECT
        C.CUSTOMER_ID,
        CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS CUSTOMER_NAME,
        SUM(OI.TOTAL_VALUE) AS TOTAL_REVENUE,
        DENSE_RANK()
            OVER (ORDER BY SUM(OI.TOTAL_VALUE) DESC) AS RNK
    FROM CUSTOMERS AS C
    LEFT JOIN ORDERS AS O
        ON
            C.CUSTOMER_ID = O.CUSTOMER_ID
    LEFT JOIN ORDER_ITEMS AS OI
        ON
            O.ORDER_ID = OI.ORDER_ID
    GROUP BY C.CUSTOMER_ID, CUSTOMER_NAME
) AS X
WHERE X.RNK <= 10;

-- The 3 customers with the fewest orders placed
SELECT
    C.CUSTOMER_ID,
    CONCAT(C.FIRST_NAME, ' ', C.LAST_NAME) AS FULL_NAME,
    COUNT(DISTINCT OI.ORDER_ID) AS TOTAL_ORDERS
FROM CUSTOMERS AS C
LEFT JOIN ORDERS AS O
    ON
        C.CUSTOMER_ID = O.CUSTOMER_ID
LEFT JOIN ORDER_ITEMS AS OI
    ON
        O.ORDER_ID = OI.ORDER_ID
GROUP BY
    C.CUSTOMER_ID,
    FULL_NAME
ORDER BY TOTAL_ORDERS ASC
LIMIT 3;
