-- Analyse sales performance over time
-- Quick Date Functions
SELECT
    EXTRACT(YEAR FROM O.ORDER_DATE) AS ORDER_YEAR,
    EXTRACT(MONTH FROM O.ORDER_DATE) AS ORDER_MONTH,
    SUM(OI.TOTAL_VALUE) AS TOTAL_REVENUE,
    COUNT(DISTINCT OI.ORDER_ID) AS TOTAL_ORDERS,
    SUM(OI.QUANTITY) AS TOTAL_QUANTITY
FROM ORDERS AS O
INNER JOIN ORDER_ITEMS AS OI
    ON
        O.ORDER_ID = OI.ORDER_ID
WHERE O.ORDER_DATE IS NOT NULL
GROUP BY ORDER_YEAR, ORDER_MONTH
ORDER BY ORDER_YEAR, ORDER_MONTH;

-- DATETRUNC()
SELECT
    DATE_TRUNC('month', O.ORDER_DATE) AS ORDER_MONTH,
    SUM(OI.TOTAL_VALUE) AS TOTAL_REVENUE,
    COUNT(DISTINCT OI.ORDER_ID) AS TOTAL_ORDERS,
    SUM(OI.QUANTITY) AS TOTAL_QUANTITY
FROM ORDERS AS O
INNER JOIN ORDER_ITEMS AS OI
    ON
        O.ORDER_ID = OI.ORDER_ID
WHERE O.ORDER_DATE IS NOT NULL
GROUP BY DATE_TRUNC('month', O.ORDER_DATE)
ORDER BY DATE_TRUNC('month', O.ORDER_DATE);

-- TO_CHAR()
SELECT
    TO_CHAR(O.ORDER_DATE, 'YYYY-MM') AS ORDER_MONTH,
    SUM(OI.TOTAL_VALUE) AS TOTAL_REVENUE,
    COUNT(DISTINCT OI.ORDER_ID) AS TOTAL_ORDERS,
    SUM(OI.QUANTITY) AS TOTAL_QUANTITY
FROM ORDERS AS O
INNER JOIN ORDER_ITEMS AS OI
    ON
        O.ORDER_ID = OI.ORDER_ID
WHERE O.ORDER_DATE IS NOT NULL
GROUP BY ORDER_MONTH
ORDER BY ORDER_MONTH ASC;
